---

- name: Download virtualbox gpg key
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    dest: "{{ ansible_user_dir }}/oracle_vbox_2016.asc"
    mode: '0440'
    force: yes

- name: De-armor gpg key
  ansible.builtin.shell: "gpg --dearmor < {{ ansible_user_dir }}/oracle_vbox_2016.asc > {{ ansible_user_dir }}/oracle_vbox_2016-archive-keyring.gpg"
  become: true

- name: Install gpg key to /usr/share/keyrings/
  ansible.builtin.shell: "install -o root -g root -m 644 {{ ansible_user_dir }}/oracle_vbox_2016-archive-keyring.gpg /usr/share/keyrings/oracle_vbox_2016-archive-keyring.gpg"
  become: true

- name: Cleanup home directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/oracle_vbox_2016.asc"
    - "{{ ansible_user_dir }}/oracle_vbox_2016-archive-keyring.gpg"

- name: Configure the hashicorp repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/oracle_vbox_2016-archive-keyring.gpg] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    filename: virtualbox
    state: present
    update_cache: yes
  become: true
