---

- name: Install minikube from google repo
  ansible.builtin.get_url:
    url : https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Import tasks for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Import tasks for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
