---

- name: Download microsoft gpg key
  ansible.builtin.get_url:
    url:  https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{ ansible_user_dir }}/microsoft.asc"
    mode: '0440'
    force: yes

- name: De-armor gpg key
  ansible.builtin.shell: "gpg --dearmor < {{ ansible_user_dir }}/microsoft.asc > {{ ansible_user_dir }}/microsoft-archive-keyring.gpg"
  become: true

- name: Install gpg key to /usr/share/keyrings/
  ansible.builtin.shell: "install -o root -g root -m 644 {{ ansible_user_dir }}/microsoft-archive-keyring.gpg /usr/share/keyrings/microsoft-archive-keyring.gpg"
  become: true

- name: Cleanup home directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/microsoft.asc"
    - "{{ ansible_user_dir }}/microsoft-archive-keyring.gpg"

- name: Configure microsoft azure-cli repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release}} main'
    filename: azure-cli
    state: present
    update_cache: yes
  become: true
