---

- name: Download hashicorp gpg key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: "{{ ansible_user_dir }}/hashicorp.gpg"
    mode: '0440'
    force: yes

- name: De-armor gpg key
  ansible.builtin.shell: "gpg --dearmor < {{ ansible_user_dir }}/hashicorp.gpg > {{ ansible_user_dir }}/hashicorp-archive-keyring.gpg"
  become: true

- name: Install gpg key to /usr/share/keyrings/
  ansible.builtin.shell: "install -o root -g root -m 644 {{ ansible_user_dir }}/hashicorp-archive-keyring.gpg /usr/share/keyrings/hashicorp-archive-keyring.gpg"
  become: true

- name: Cleanup home directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/hashicorp.gpg"
    - "{{ ansible_user_dir }}/hashicorp-archive-keyring.gpg"

- name: Configure the hashicorp repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
    filename: hashicorp
    state: present
    update_cache: yes
  become: true
