---

- name: Add vscode repository
  ansible.builtin.yum_repository:
    name: vscode
    description: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode
  become: true

- name: Install vscode
  ansible.builtin.yum:
    name: ['code']
    state: present
  become: true