---

- include_tasks: debian_repo.yml

- name: Install docker + containerd + docker-compose-plugin
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present
  become: true

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750
  become: true

- name: Add user to "docker" group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: ['docker']
    append: yes
  become: true
