---

- name: Download podman gpg key
  ansible.builtin.get_url:
    url:  https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
    dest: "{{ ansible_user_dir }}/podman.key"
    mode: '0440'
    force: yes

- name: De-armor gpg key
  ansible.builtin.shell: "gpg --dearmor < {{ ansible_user_dir }}/podman.key > {{ ansible_user_dir }}/podman-archive-keyring.gpg"
  become: true

- name: Install gpg key to /usr/share/keyrings/
  ansible.builtin.shell: "install -o root -g root -m 644 {{ ansible_user_dir }}/podman-archive-keyring.gpg /usr/share/keyrings/podman-archive-keyring.gpg"
  become: true

- name: Cleanup home directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/podman.key"
    - "{{ ansible_user_dir }}/podman-archive-keyring.gpg"

- name: Configure podman repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/podman-archive-keyring.gpg] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /'
    filename: podman
    state: present
    update_cache: yes
  become: true
