---

- name: Add docker-ce repository
  become: true
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  become: true
  ansible.builtin.yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present

- name: Add user to "docker" group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: ["docker"]
    append: yes
