---

- hosts: ['localhost','all']
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - include: playbooks/main.yml

  roles:
    - role: common/ansible_facts
    - role: tools/vscode
    - role: virtualisation/virtualbox
    - role: tools/hashicorp
    - role: container/minikube
    - role: container/podman
    - role: container/docker
    - role: cloud/aws-cli
    - role: cloud/azure-cli
    - role: cloud/gcloud-cli
